# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='storage/')),
                ('artist', models.CharField(default='Unknown', max_length=200)),
                ('title', models.CharField(default='Unknown', max_length=200)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='BPM',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('description', models.CharField(default='Please, fill in description field', max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessQuery',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('priority', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('date_queued', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date queued')),
                ('parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Parameter')),
                ('pla', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uploader.PreLoadedAudio')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('date_queued', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date queued')),
                ('priority', models.IntegerField()),
                ('query', models.CharField(default='N/A', max_length=4000)),
            ],
        ),
    ]
