# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreLoadedAudio',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='not_processed/')),
                ('priority', models.IntegerField(default=0)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date uploaded')),
                ('status', models.CharField(default='Ready to process', max_length=200)),
            ],
        ),
    ]
