# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_text', models.CharField(max_length=200)),
                ('disk_usage', models.CharField(max_length=200)),
                ('cpu_usage', models.CharField(max_length=200)),
                ('date_query', models.DateTimeField(verbose_name='date query')),
            ],
        ),
    ]
