# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='cpu_usage',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='date_query',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='disk_usage',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='stats_text',
        ),
    ]
